# Generated by Django 3.2 on 2021-05-01 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_register', '0002_alter_blog_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='img',
        ),
    ]
