# Generated by Django 3.2 on 2021-05-02 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_register', '0003_remove_blog_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='img',
            field=models.ImageField(default='null', upload_to='images/'),
            preserve_default=False,
        ),
    ]
